-- ============================================================================
-- V1 - initial schema for the feedback platform
--
-- Foreign keys point from the child (feedback) to its parents (student, course),
-- correcting the direction of the original draft SQL.
-- ============================================================================

CREATE TABLE student (
    id                  UUID PRIMARY KEY,
    name                VARCHAR(255),
    registration_number VARCHAR(255),
    auth_id             UUID
);

CREATE TABLE admin (
    id      UUID PRIMARY KEY,
    name    VARCHAR(255),
    auth_id UUID,
    role    VARCHAR(255)
);

CREATE TABLE course (
    id   UUID PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE feedback (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id         UUID REFERENCES student (id),
    course_id          UUID REFERENCES course (id),
    score              INT CHECK (score BETWEEN 0 AND 10),
    review_description VARCHAR(255),
    review_date        TIMESTAMPTZ,
    notified           BOOLEAN DEFAULT FALSE,
    notified_date      TIMESTAMPTZ
);

-- Lookups by auth_id (resolving the caller from the JWT) and by student.
CREATE INDEX idx_student_auth_id ON student (auth_id);
CREATE INDEX idx_admin_auth_id ON admin (auth_id);
CREATE INDEX idx_feedback_student_id ON feedback (student_id);

-- Default course every feedback is attached to (see app.default-course-id).
INSERT INTO course (id, name)
VALUES ('00000000-0000-0000-0000-000000000001', 'General');
