
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build
COPY . .
RUN mvn -B -pl notification-function -am package -DskipTests

FROM mcr.microsoft.com/azure-functions/java:4-java21-appservice

COPY --from=build /build/notification-function/target/azure-functions/rate-me-notification-function/ /home/site/wwwroot/

ADD https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.7.8/applicationinsights-agent-3.7.8.jar /home/site/wwwroot/applicationinsights-agent.jar
RUN chmod 644 /home/site/wwwroot/applicationinsights-agent.jar

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    APPLICATIONINSIGHTS_ROLE_NAME=notification-function \
    LOG_SCAN_SCHEDULE="0 */5 * * * *"
