
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build
COPY . .
RUN mvn -B -pl feedback-service -am package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /build/feedback-service/target/quarkus-app/ ./
ADD https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.7.8/applicationinsights-agent-3.7.8.jar /app/applicationinsights-agent.jar
ENV APPLICATIONINSIGHTS_ROLE_NAME="feedback-service"
EXPOSE 8086
ENTRYPOINT ["java", "-javaagent:/app/applicationinsights-agent.jar", "-jar", "quarkus-run.jar"]
